boythesda/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import the_boythesda
from boythesda import settings
from the_boythesda import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('user/', include('userstuff.urls')),

    url(r'^searchGame/$', views.searchGame, name='searchGame'),

    url(r'^cart/', include('cart.urls'), name='cart'),

    url(r'^order/', include('orders.urls'), name='orders'),
    ######
    path('', include('the_boythesda.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^add/(?P<game_pk>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<game_pk>\d+)/$', views.cart_remove, name='cart_remove'),

    url(r'^$', views.cart_detail, name='cart_detail'),
]

the_boythesda/urls.py
from django.conf.urls import url
from django.urls import path

from the_boythesda import views, staff_views

from userstuff import views as userviews

urlpatterns = [
    path('', views.GameListView.as_view(), name = 'main'),

    url(r'^game/(?P<pk>\d+)/$', views.GameDetailView, name = 'game'),

    url(r'^publishers/$', views.PublisherListView.as_view(), name = 'publishers'),
    url(r'^publisher/(?P<pk>\d+)/$', views.PublisherDetailView.as_view(), name = 'publisher'),

    url(r'^about_us/$', views.AboutUs, name = 'about_us'),

    url(r'^games_of_genre/(?P<genre_id>\d+)/$', views.GamesOfGenre, name= 'games_of_genre'),

    url(r'^admin_users_page/$', staff_views.AllUsersView, name='admin_users'),
    url(r'^admin_games_page/$', staff_views.AllGamesView.as_view(), name = 'admin_games'),

    url(r'^userpage_update/(?P<user_id>\d+)$', staff_views.UserUpdateView, name='user_update'),
    url(r'^userpage_delete/(?P<user_id>\d+)$', staff_views.UserDeleteView, name = 'user_delete'),

    url(r'^gamepage_create/$', staff_views.GameCreateView.as_view(), name='game_create'),
    url(r'^gamepage_update/(?P<pk>\d+)$', staff_views.GameUpdateView.as_view(), name='game_update'),
    url(r'^gamepage_delete/(?P<game_id>\d+)$', staff_views.GameDeleteView, name='game_delete'),

    url(r'^genre_create/$', staff_views.GenreCreateView.as_view(), name = 'genre_create'),

    url(r'^publisher_create/$', staff_views.PublisherCreateView.as_view(), name = 'publisher_create'),
    url(r'^publisher_update/(?P<pk>\d+)$', staff_views.PublisherUpdateView.as_view(), name = 'publisher_update'),

    url(r'^system_req_create/$', staff_views.SysReqCreateView.as_view(), name = 'system_req_create'),
    url(r'^system_req_update/(?P<pk>\d+)$', staff_views.SysReqUpdateView.as_view(), name = 'system_req_update'),

]

the_boythesda/models.py
from django.db import models

# Create your models here.
from django.utils.safestring import mark_safe


class Game(models.Model):
    title = models.CharField(max_length=200, help_text='Название игры', verbose_name='Название игры')
    summary = models.TextField(default='Нет описания', help_text='Описание игры', verbose_name='Описание игры')
    releaseDate = models.DateField(null=True, blank=True)
    price = models.FloatField(max_length=9999.00, default=0.0, verbose_name='Цена', help_text='Цена игры', null=True, blank=True)
    Image = models.ImageField(upload_to='gamePages/', null = True, blank=True,)
    scoreCritics = models.IntegerField(help_text='Средняя оценка критиков', null = True, blank= True)
    scoreUsers = models.IntegerField(help_text='Средняя оценка пользователей', null = True, blank = True)

    publisher = models.ForeignKey('Publisher', help_text='Издатель', on_delete=models.SET_DEFAULT, default= 'Издатель отсутствует или был удален')
    sysReq = models.ForeignKey('SysReq', verbose_name='Системные требования (Рекомендуемые)', on_delete=models.CASCADE)
    genre = models.ManyToManyField('Genre', verbose_name='Жанр(ы)')

    class Meta:
        verbose_name = 'Игра'
        db_table = 'GAME'

    def __str__(self):
        return self.title

    def summary_short(self):
        summary_list = self.summary.split(' ')
        i = len(summary_list)
        if i > 30: i = 30
        elif i == 0: return "Описания нет."
        short_sum = ' '.join(summary_list[0:i])
        return short_sum + '...'




class Publisher(models.Model):
    name = models.CharField(max_length=200, help_text='Издатель', verbose_name='Издатель', unique=True)
    summary = models.TextField(help_text='Описание издателя', null= True, blank=True, default='Нет описания')
    foundation_date = models.DateField(verbose_name='Год основания', blank=True, null = True)

    class Meta:
        db_table = 'PUBLISHER'

    def __str__(self):
        return self.name



class Genre(models.Model):
    name = models.CharField(max_length=100, verbose_name='Жанр', default='Жанр не указан', unique=True)

    class Meta:
        db_table = 'GENRE'

    def __str__(self):
        return self.name

class SysReq(models.Model):
    configuration_name = models.CharField(max_length=200, null = True, blank= True)
    HDD = models.CharField(max_length=300, help_text='Место на жестком диске', verbose_name='Место на жестком диске')
    CPU = models.CharField(max_length=300, help_text='Процессор', verbose_name='Рекоментуемый процессор')
    GPU = models.CharField(max_length=300, help_text='Видеокарта', verbose_name='Рекоментуемая видеокарта')
    DDR = models.SmallIntegerField(help_text='Объем оперативной памяти (Гб)', verbose_name='Объем оперативной памяти (Гб)')

    class Meta:
        db_table = 'SYSREQ'

    def __str__(self):
        if self.configuration_name == None:
            return 'Конфигурация #{}' .format(self.id)
        else: return self.configuration_name

the_boythesda/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import DateField

from boythesda import settings
from the_boythesda.models import Genre, Game
from userstuff.forms import UserForm
from userstuff.models import UserProfile


class SearchForm(forms.Form):
    query = forms.CharField()

class GenreChoiceForm(forms.ModelForm):
    genres = forms.ModelMultipleChoiceField(queryset=Genre.objects.all(),
                                            required=False,
                                            widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-check'})
                                            )
    class Meta:
        model = Genre
        exclude = ['id', 'name']

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'is_staff', 'is_superuser')
        exclude = ['password']

'''
class GameUpdateForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['title', 'summary', 'genre', 'price', 'scoreCritics', 'scoreUsers', 'publisher', 'Image',
                  'releaseDate','sysReq']
        widgets = {'releaseDate': DateField(input_formats=settings.DATE_INPUT_FORMATS)}
'''

the_boythesda/views.py
import math

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from django.http import Http404
from django.shortcuts import render, render_to_response, get_object_or_404

# Create your views here.
from django.views import generic
from django.views.generic.edit import FormMixin


from the_boythesda.forms import GenreChoiceForm
from the_boythesda.models import Game, Publisher, Genre, SysReq
from django.utils.translation import gettext as _
from userstuff.views import login

from cart.forms import CartAddProductForm

class FormListView(generic.list.ListView, FormMixin):

    def get(self, request, *args, **kwargs):
        # From ProcessFormMixin
        form_class = self.get_form_class()
        self.form = self.get_form(form_class)

        # From BaseListView
        self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty and len(self.object_list) == 0:
            raise Http404(_(u"Empty list and '%(class_name)s.allow_empty' is False.")
                          % {'class_name': self.__class__.__name__})

        context = self.get_context_data(object_list=self.object_list, form=self.form)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)


class GameListView(FormListView):
    model = Game
    ordering = ['releaseDate', 'scoreUsers']
    template_name = 'mainpage.html'
    paginate_by = 10
    form_class = GenreChoiceForm
    context_object_name = 'game_list'
    #success_url = '/filtered-games'

    def get_context_data(self, **kwargs):
        context = super(GameListView, self).get_context_data(**kwargs)
        context['all_genres'] = Genre.objects.all()
        context['genres_form'] = self.form

        if not context.get('is_paginated', False):
            return context

        paginator = context.get('paginator')
        num_pages = paginator.num_pages
        current_page = context.get('page_obj')
        page_no = current_page.number

        if num_pages <= 11 or page_no <= 6:
            pages = [x for x in range(1, min(num_pages + 1, 12))]
        elif page_no > num_pages - 6:
            pages = [x for x in range(num_pages - 10, num_pages + 1)]
        else:
            pages = [x for x in range(page_no - 5, page_no + 6)]

        context.update({'pages': pages})

        if self.form.is_valid():
            data = self.form.cleaned_data

            if len(data['genres']) == 0: context['game_list'] = Game.objects.all()
            else:
                gg = Game.objects.filter(genre__name__contains= list(data['genres'])[0])
                for i in range(1, len(list(data['genres']))):
                    gg = gg.filter(genre__name__contains=list(data['genres'])[i])
                context['game_list'] = gg

        return context


class GameDetailView_2(generic.DetailView):

    model = Game
    template_name = 'individual_pages/games/game.html'
    cart_product_form = CartAddProductForm()

class PublisherListView(generic.ListView):
    model = Publisher
    template_name = 'list_pages/publishers.html'
    paginate_by = 10

class PublisherDetailView(generic.DetailView):
    model = Publisher
    template_name = 'individual_pages/publishers/publisher.html'

def searchGame(req):
    errors = []
    if 'q' in req.GET:
        q = req.GET['q']
        if not q:
            errors.append('Ошибка: пустое поле')
        elif len(q) > 100:
            errors.append('Введите не более 100 символов!')
        else:
            games = Game.objects.filter(title__icontains=q)
            publishers = Publisher.objects.filter(name__contains=q)
            genres = Genre.objects.filter(name__contains=q)
            context = {'games' : games, 'publishers' : publishers, 'genres' : genres, 'query': q}
            return render_to_response('list_pages/games_search_result.html', context)

    return render_to_response('list_pages/games_search_result.html',
                              {'errors': errors})


def GameDetailView(req, pk):
    game = get_object_or_404(Game, pk=pk)
    cart_product_form = CartAddProductForm
    return render(req, 'individual_pages/games/game.html', {'game': game, 'cart_product_form': cart_product_form})

def AboutUs(req):
    return render(req, 'aboutUs.html')


def GamesOfGenre(req, genre_id):
    genre = Genre.objects.get(id = genre_id)
    games_with_genre = Game.objects.filter(genre__name__contains=genre)

    paginator = Paginator(games_with_genre, 10)
    page = req.GET.get('page')

    try:
        games = paginator.page(page)
    except PageNotAnInteger:
        games = paginator.page(1)
    except EmptyPage:
        games = paginator.page(paginator.num_pages)
    if paginator.num_pages <= 11 or games.number <= 6:
        pages = [x for x in range(1, min(paginator.num_pages + 1, 12))]
    elif games.number > paginator.num_pages - 6:
        pages = [x for x in range(paginator.num_pages - 10, paginator.num_pages + 1)]
    else:
        pages = [x for x in range(games.number - 5, games.number + 6)]
    return render(req, 'list_pages/gamesWithGenre.html', {'games': games,
                                                          'pages': pages})

the_boythesda/templates/staff_pages/games/game_create.html
{% extends 'basic.html' %}

{% block content %}
    <form action="{% url 'game_create' %}" method="POST">
    {% if form.errors %}
       {% for field in form %}
           {% for error in field.errors %}
               <div class="alert alert-danger">
                   <strong>{{ error|escape }}</strong>
               </div>
            {% endfor %}
       {% endfor %}
       {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
       {% endfor %}
    {% endif %}
    {% csrf_token %}
        <table>
            <tr>
                <th>
                    <label for="id_title">Название игры:</label>
                </th>
                <td>
                    <input type="text" name="title" maxlength="200" required id="id_title">
                    <br><span class="helptext">Название игры</span>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_summary">Описание игры:</label>
                </th>
                <td>
                    <textarea name="summary" cols="40" rows="10" required id="id_summary">Нет описания</textarea>
                    <br><span class="helptext">Описание игры</span>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_genre">Жанр(ы):</label>
                </th>
                <td>
                    {{ form.genre }} <a href = '{% url 'genre_create' %}'><i class="fas fa-plus-square" ></i></a>

                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_price">Цена:</label></th>
                <td>
                    <input type="number" name="price" value="0.0" step="any" id="id_price">
                    <br><span class="helptext">Цена игры</span>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_scoreCritics">ScoreCritics:</label></th>
                <td>
                    <input type="number" name="scoreCritics" id="id_scoreCritics">
                    <br><span class="helptext">Средняя оценка критиков</span>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_scoreUsers">ScoreUsers:</label>
                </th>
                <td>
                    <input type="number" name="scoreUsers" id="id_scoreUsers">
                    <br><span class="helptext">Средняя оценка пользователей</span>
            </td>
            </tr>
            <tr>
                <th>
                    <label for="id_publisher">Publisher:</label>
                </th>
                <td>
                    {{ form.publisher }} <a href = '{% url 'publisher_create' %}'><i class="fas fa-plus-square" ></i></a>
                    {% if game.publisher %}
                    <a href = '{% url 'publisher_update' game.publisher.pk %}'><i class="fas fa-pen"></i></a>
                    {% endif %}
                    <br><span class="helptext">Издатель</span>
                </td>
            </tr>

            <tr>
                <th>
                    <label for="id_Image">Image:</label>
                </th>
                <td>
                    <input type="file" name="Image" accept="image/*" id="id_Image">
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_releaseDate">ReleaseDate:</label>
                </th>
                <td>
                    <input type="text" name="releaseDate" id="id_releaseDate">
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_sysReq">Системные требования (Рекомендуемые):</label>
                </th>
                <td>
                    {{ form.sysReq }} <a href = '{% url 'system_req_create'%}'  ><i class="fas fa-plus-square" ></i></a>
                    {% if game.sysReq %}
                    <a href = '{% url 'system_req_update' game.sysReq.pk %}' ><i class="fas fa-pen"></i></a>
                    {% endif %}
                </td>
            </tr>
        </table>
        <input type="submit" class = 'btn btn-secondary btn-sm' value="Сохранить игру">
    </form>
        <a href = '{% url 'admin_games' %}'><button class="btn btn-secondary mt-2 btn-sm">Назад</button></a>
{% endblock %}

the_boythesda/templates/staff_pages/games/game_update.html
{% extends 'basic.html' %}

{% block content %}
    <form action="{% url 'game_update' game.id %}" method="POST">
    {% if form.errors %}
       {% for field in form %}
           {% for error in field.errors %}
               <div class="alert alert-danger">
                   <strong>{{ error|escape }}</strong>
               </div>
            {% endfor %}
       {% endfor %}
       {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
       {% endfor %}
    {% endif %}
    {% csrf_token %}
        <table>
            <tr>
                <th>
                    <label for="id_title">Название игры:</label>
                </th>
                <td>
                    <input type="text" name="title" maxlength="200" required id="id_title" value="{{ game.title }}">
                    <br><span class="helptext">Название игры</span>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_summary">Описание игры:</label>
                </th>
                <td>
                    <textarea name="summary" cols="40" rows="10" required id="id_summary" >{{ game.summary }}</textarea>
                    <br><span class="helptext">Описание игры</span>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_genre">Жанр(ы):</label>
                </th>
                <td>
                    {{ form.genre }} <a href = '{% url 'genre_create' %}'><i class="fas fa-plus-square" ></i></a>

                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_price">Цена:</label></th>
                <td>
                    <input type="number" name="price" value="{{ game.price }}" step="any" id="id_price" >
                    <br><span class="helptext">Цена игры</span>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_scoreCritics">ScoreCritics:</label></th>
                <td>
                    <input type="number" name="scoreCritics" id="id_scoreCritics" value="{{ game.scoreCritics }}">
                    <br><span class="helptext">Средняя оценка критиков</span>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_scoreUsers">ScoreUsers:</label>
                </th>
                <td>
                    <input type="number" name="scoreUsers" id="id_scoreUsers" value = '{{ game.scoreUsers }}'>
                    <br><span class="helptext">Средняя оценка пользователей</span>
            </td>
            </tr>
            <tr>
                <th>
                    <label for="id_publisher">Publisher:</label>
                </th>
                <td>
                    {{ form.publisher }} <a href = '{% url 'publisher_create' %}><i class="fas fa-plus-square" ></i></a>
                    <a href = '{% url 'publisher_update' game.publisher.pk %}'><i class="fas fa-pen"></i></a>
                    <br><span class="helptext">Издатель</span>
                </td>
            </tr>

            <tr>
                <th>
                    <label for="id_Image">Image:</label>
                </th>
                <td>
                    <input type="file" name="Image" accept="image/*" id="id_Image" value="{{ game.Image }}">
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_releaseDate">ReleaseDate:</label>
                </th>
                <td>
                    <input type="date" name="releaseDate" id="id_releaseDate" value = '{{ game.releaseDate|date:"Y-m-d" }}'>
                </td>
            </tr>
            <tr>
                <th>
                    <label for="id_sysReq">Системные требования (Рекомендуемые):</label>
                </th>
                <td>
                    {{ form.sysReq }} <a href = '{% url 'system_req_create'%}'><i class="fas fa-plus-square" ></i></a>
                    <a href = '{% url 'system_req_update' game.sysReq.pk %}'><i class="fas fa-pen"></i></a>
                </td>
            </tr>
        </table>
        <input type="submit" class = 'btn btn-secondary btn-sm' value="Сохранить">
    </form>
    <a href = '{% url 'game_delete' game.id %}'><button class="btn btn-secondary mt-2 btn-sm">Удалить игру</button></a>
    <a href = '{% url 'admin_games' %}'><button class="btn btn-secondary mt-2 btn-sm">Назад</button></a>
{% endblock %}

the_boythesda/templates/staff_pages/games/genre_create.html
{% extends 'basic.html' %}

{% block content %}
    <form action="{% url 'genre_create'%}" method="POST">
    {% csrf_token %}
    {% if form.errors %}
        {% for error in form.errors %}
            {{ error }}
        {% endfor %}
    {% endif %}
    <table>
        {{ form.as_table }}
    </table>
    <input type = 'submit' class = 'btn btn-secondary btn-sm' value="Подтвердить">
    </form>
    <a href = '{% url 'game_create' %}'><button class="btn btn-secondary mt-2 btn-sm">Назад</button></a>
{% endblock %}

the_boythesda/templates/staff_pages/games/publisher_create.html
{% extends 'basic.html' %}

{% block content %}
    <form action="{% url 'publisher_create'%}" method="POST">
    {% csrf_token %}
    {% if form.errors %}
        {% for error in form.errors %}
            {{ error }}
        {% endfor %}
    {% endif %}
    <table>
        {{ form.as_table }}
    </table>
    <input type = 'submit' class = 'btn btn-secondary btn-sm' value="Подтвердить">
    </form>
    <a href = '{% url 'game_create' %}'><button class="btn btn-secondary mt-2 btn-sm">Назад</button></a>
{% endblock %}

the_boythesda/templates/staff_pages/games/publisher_update.html
{% extends 'basic.html' %}

{% block content %}
    <form action="" method="POST">
    {% csrf_token %}
    {% if form.errors %}
        {% for error in form.errors %}
            {{ error }}
        {% endfor %}
    {% endif %}
    <table>
        {{ form.as_table }}
    </table>
    <input type = 'submit' class = 'btn btn-secondary btn-sm' value="Подтвердить">
    </form>
    <a href = '{% url 'game_create' %}'><button class="btn btn-secondary mt-2 btn-sm">Назад</button></a>
{% endblock %}

the_boythesda/templates/staff_pages/games/staff_games_page.html
{% extends 'basic.html' %}

{% block content %}
    <div class = 'container-fluid'>
        <div class = 'row'>
            <div class = ''>
                <h3>Вы вошли как {{ user.username }}.</h3>
                {% if user.is_superuser %}
                    <h6>Вы обладаете правами <b>Суперпользователя</b>.</h6>
                    <h6>Вам доступны функции добавления, редактирования и удаления товаров, а также редактирование списка других пользователей</h6>
                {% elif user.is_staff%}
                    <h6>Вы обладаете правами <b>Администратора</b>.</h6>
                    <h6>Вам доступны функции добавления, редактирования и удаления товаров, а также просмотр списка других пользователей.</h6>
                {% endif %}
            <a href="{% url 'admin_users' %}" class="btn btn-secondary" role="button" aria-disabled="true">Пользователи</a>
            <a href="#" class="btn btn-secondary disabled" role="button" aria-disabled="true">Товары</a>
            <a href="{% url 'game_create' %}" class="btn btn-secondary" style="float: right" role="button" aria-disabled="true">Добавить игру</a>
            <table class = 'table mt-4'>
            <tr>
                <th>id</th>
                <th>Название</th>
                <th>Обложка</th>
                <th>Дата выхода</th>
                <th>Издатель</th>
                <th>Жанры</th>
            {% if user.is_superuser or user.is_staff %}
                <th>Редактирование</th>
            {% endif %}
            </tr>
            {% for game in games %}
            <tr>
                <td>{{ game.id }}</td>
                <td>{{ game.title }}</td>
                {% if game.Image %}
                <td><img class = 'img-fluid' style="max-width: 100px" src = '{{ game.Image.url }}' alt = 'Обложка'></td>
                {% else %}
                    <td><p>Изображение отсутствует</p></td>
                {% endif %}
                <td>
                    {% if game.releaseDate %}
                        {{ game.releaseDate }}
                    {% else %}
                        <p>Дата не указана</p>
                    {% endif %}
                </td>
                <td>{{ game.publisher.name }}</td>
                <td>{% for genre in game.genre.all %}
                    {{ genre.name }};
                    {% endfor %}
                    </td>
            {% if user.is_staff %}
                <td><a type="btn btn-secondary" href = '{% url 'game_update' game.pk %}'>Редактирование</a></td>
            {% endif %}
            </tr>
        {% endfor %}
        </table>
            </div>
        </div>
    </div>

    {% if is_paginated %}

            <nav aria-label="Список страниц" class="text-center">
                <ul class="pagination justify-content-center">

                    {% if page_obj.has_previous %}
                        <li class="page-item"><a class = "page-link" href = "?page={{ page_obj.previous_page_number }}">Назад</a></li>
                    {% endif %}

                    {% for num in pages %}
                        {% if num == page_obj.number %}
                            <li class="page-item active"><a class="page-link">{{ num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{num}}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item"><a class = "page-link" href = "?page={{ page_obj.next_page_number }}">Вперед</a></li>
                    {% endif %}

                </ul>
            </nav>
        {% endif %}

{% endblock %}

the_boythesda/templates/staff_pages/games/system_req_create.html
{% extends 'basic.html' %}

{% block content %}
    <form action="{% url 'system_req_create'%}" method="POST">
    {% csrf_token %}
    {% if form.errors %}
        {% for error in form.errors %}
            {{ error }}
        {% endfor %}
    {% endif %}
    <table>
        {{ form.as_table }}
    </table>
    <input type = 'submit' class = 'btn btn-secondary btn-sm' value="Подтвердить">
    </form>
    <a href = '{% url 'game_create' %}'><button class="btn btn-secondary mt-2 btn-sm">Назад</button></a>
{% endblock %}

the_boythesda/templates/staff_pages/games/system_req_update.html
{% extends 'basic.html' %}

{% block content %}
    <form action="" method="POST">
    {% csrf_token %}
    {% if form.errors %}
        {% for error in form.errors %}
            {{ error }}
        {% endfor %}
    {% endif %}
    <table>
        {{ form.as_table }}
    </table>
    <input type = 'submit' class = 'btn btn-secondary btn-sm' value="Подтвердить">
    </form>
    <a href = '{% url 'game_create' %}'><button class="btn btn-secondary mt-2 btn-sm">Назад</button></a>
{% endblock %}